---
name: WWW-FreeProxyListsCom
version: 0.002
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: get proxy lists from http://www.freeproxylists.com
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  Devel::TakeHashArgs: 0.001
  HTML::Entities: 1.35
  HTML::TokeParser::Simple: 3.15
  URI: 1.35
  WWW::Mechanize: 1.34
build_requires:
  Test::More: 0
provides:
  WWW::FreeProxyListsCom:
    file: lib/WWW/FreeProxyListsCom.pm
    version: 0.002
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
