---
abstract: 'get proxy lists from http://www.freeproxylists.com'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-FreeProxyListsCom
provides:
  WWW::FreeProxyListsCom:
    file: lib/WWW/FreeProxyListsCom.pm
    version: 0.003
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  Devel::TakeHashArgs: 0.001
  HTML::Entities: 1.35
  HTML::TokeParser::Simple: 3.15
  URI: 1.35
  WWW::Mechanize: 1.34
resources:
  license: http://dev.perl.org/licenses/
version: 0.003
